package com.mindzone.enums;

public enum Approach {

    BEHAVIORISM, COGNITIVE, HUMANISTIC,
    PSYCHOANALYSIS, EXISTENTIAL, GESTALT,
    EVOLUTIONARY, SOCIAL, BIOPSYCHOLOGY,
    POSITIVE, BIOLOGICAL, PSYCHODYNAMIC,
    INTERPERSONAL, SYSTEMS, ECLETIC,
    TRAUMA_INFORMED, INTEGRATIVE
}
