package com.mindzone.enums;

public enum Speciality {

    CLINICAL, COUNSELING, DEVELOPMENTAL, FORENSIC, INDUSTRIAL_ORGANIZATIONAL, EDUCATIONAL, NEUROPSYCHOLOGY,
    HEALTH, SOCIAL, SPORTS, CHILDHOOD, YOUTH, GERIATRIC, ADDICTION, CONSULTATION_LIAISON,
    EMERGENCY, PSYCHOSOMATIC, NEUROPSYCHIATRY, MOOD_DISORDERS, PSYCHOTIC_DISORDERS
}
